// Generated by scripts/generate-icons.py from artwork/icon-monochrome.svg.
package com.satori.qq.core;

import android.graphics.Bitmap;
import android.graphics.Canvas;
import android.graphics.Color;
import android.graphics.Paint;
import android.graphics.Path;
import android.graphics.drawable.Icon;

/** Cached alpha icon: safe to use from the QQ host context on API 26+. */
final class StatusIcon {
    private static Icon cached;
    static synchronized Icon get() {
        if (cached != null) return cached;
        Bitmap bitmap = Bitmap.createBitmap(96, 96, Bitmap.Config.ARGB_8888);
        Canvas canvas = new Canvas(bitmap);
        canvas.scale(96f / 69f, 96f / 69f);
        canvas.translate(-19.5f, -21f);
        Paint paint = new Paint(Paint.ANTI_ALIAS_FLAG);
        paint.setColor(Color.WHITE);
        paint.setStrokeCap(Paint.Cap.ROUND);
        paint.setStrokeJoin(Paint.Join.ROUND);
        Path path = new Path();
        path.reset();
        path.moveTo(28f, 56f);
        path.quadTo(41f, 28f, 54f, 56f);
        path.quadTo(67f, 84f, 80f, 56f);
        paint.setStyle(Paint.Style.STROKE);
        paint.setStrokeWidth(13f);
        canvas.drawPath(path, paint);
        cached = Icon.createWithBitmap(bitmap);
        return cached;
    }
    private StatusIcon() {}
}
