// Generated by scripts/generate-icons.py from artwork/icon-monochrome.svg.
package com.satori.qq.core;

import android.graphics.Bitmap;
import android.graphics.Canvas;
import android.graphics.Color;
import android.graphics.Paint;
import android.graphics.Path;
import android.graphics.drawable.Icon;

/** Cached alpha icon: safe to use from the QQ host context on API 26+. */
final class StatusIcon {
    private static Icon cached;
    static synchronized Icon get() {
        if (cached != null) return cached;
        Bitmap bitmap = Bitmap.createBitmap(96, 96, Bitmap.Config.ARGB_8888);
        Canvas canvas = new Canvas(bitmap);
        canvas.scale(96f / 56f, 96f / 56f);
        canvas.translate(-26, -27);
        Paint paint = new Paint(Paint.ANTI_ALIAS_FLAG);
        paint.setColor(Color.WHITE);
        Path path = new Path();
        path.setFillType(Path.FillType.EVEN_ODD);
        path.moveTo(43f, 31f);
        path.lineTo(60f, 31f);
        path.quadTo(72f, 31f, 72f, 43f);
        path.lineTo(72f, 47f);
        path.lineTo(68f, 47f);
        path.lineTo(68f, 43f);
        path.quadTo(68f, 35f, 60f, 35f);
        path.lineTo(43f, 35f);
        path.quadTo(34f, 35f, 34f, 44f);
        path.lineTo(34f, 48f);
        path.quadTo(34f, 53f, 37f, 55f);
        path.lineTo(37f, 59f);
        path.lineTo(42f, 56f);
        path.lineTo(46f, 56f);
        path.lineTo(46f, 60f);
        path.lineTo(43f, 60f);
        path.lineTo(33f, 67f);
        path.lineTo(33f, 57f);
        path.quadTo(30f, 54f, 30f, 48f);
        path.lineTo(30f, 44f);
        path.quadTo(30f, 31f, 43f, 31f);
        path.close();
        path.moveTo(41f, 41f);
        path.lineTo(60f, 41f);
        path.quadTo(62f, 41f, 62f, 43f);
        path.quadTo(62f, 45f, 60f, 45f);
        path.lineTo(41f, 45f);
        path.quadTo(39f, 45f, 39f, 43f);
        path.quadTo(39f, 41f, 41f, 41f);
        path.close();
        path.moveTo(59f, 51f);
        path.lineTo(66f, 51f);
        path.quadTo(78f, 51f, 78f, 63f);
        path.lineTo(78f, 65f);
        path.quadTo(78f, 71f, 75f, 73f);
        path.lineTo(75f, 79f);
        path.lineTo(66f, 75f);
        path.lineTo(59f, 75f);
        path.quadTo(49f, 75f, 49f, 65f);
        path.lineTo(49f, 62f);
        path.quadTo(49f, 51f, 59f, 51f);
        path.close();
        path.moveTo(59f, 55f);
        path.quadTo(53f, 55f, 53f, 62f);
        path.lineTo(53f, 65f);
        path.quadTo(53f, 71f, 59f, 71f);
        path.lineTo(67f, 71f);
        path.lineTo(71f, 73f);
        path.lineTo(71f, 71f);
        path.quadTo(74f, 69f, 74f, 65f);
        path.lineTo(74f, 63f);
        path.quadTo(74f, 55f, 66f, 55f);
        path.close();
        path.moveTo(58f, 60f);
        path.lineTo(68f, 60f);
        path.quadTo(70f, 60f, 70f, 62f);
        path.quadTo(70f, 64f, 68f, 64f);
        path.lineTo(58f, 64f);
        path.quadTo(56f, 64f, 56f, 62f);
        path.quadTo(56f, 60f, 58f, 60f);
        path.close();
        canvas.drawPath(path, paint);
        cached = Icon.createWithBitmap(bitmap);
        return cached;
    }
    private StatusIcon() {}
}
