// Generated by scripts/generate-icons.py from artwork/icon-monochrome.svg.
package com.satori.qq.core;

import android.graphics.Bitmap;
import android.graphics.Canvas;
import android.graphics.Color;
import android.graphics.Paint;
import android.graphics.Path;
import android.graphics.drawable.Icon;

/** Cached alpha icon: safe to use from the QQ host context on API 26+. */
final class StatusIcon {
    private static Icon cached;
    static synchronized Icon get() {
        if (cached != null) return cached;
        Bitmap bitmap = Bitmap.createBitmap(96, 96, Bitmap.Config.ARGB_8888);
        Canvas canvas = new Canvas(bitmap);
        canvas.scale(96f / 62.68f, 96f / 62.68f);
        canvas.translate(-22.66f, -22.66f);
        Paint paint = new Paint(Paint.ANTI_ALIAS_FLAG);
        paint.setColor(Color.WHITE);
        paint.setStrokeCap(Paint.Cap.ROUND);
        paint.setStrokeJoin(Paint.Join.ROUND);
        Path path = new Path();
        path.reset();
        path.moveTo(73.57f, 37.96f);
        path.cubicTo(70.01f, 34.22f, 63.7f, 32.47f, 57.67f, 33.56f);
        path.cubicTo(51.65f, 34.64f, 47.14f, 38.33f, 46.33f, 42.86f);
        path.cubicTo(45.52f, 47.38f, 48.56f, 51.8f, 54f, 54f);
        path.cubicTo(59.44f, 56.2f, 62.48f, 60.62f, 61.67f, 65.14f);
        path.cubicTo(60.86f, 69.67f, 56.35f, 73.36f, 50.33f, 74.44f);
        path.cubicTo(44.3f, 75.53f, 37.99f, 73.78f, 34.43f, 70.04f);
        paint.setStyle(Paint.Style.STROKE);
        paint.setStrokeWidth(12.39f);
        canvas.drawPath(path, paint);
        cached = Icon.createWithBitmap(bitmap);
        return cached;
    }
    private StatusIcon() {}
}
